# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nomClient', models.CharField(max_length=100)),
                ('prenomClient', models.CharField(max_length=100)),
                ('nomFournisseur', models.CharField(max_length=100)),
                ('prenomFournisseur', models.CharField(max_length=100)),
                ('nombrePagesCouleur', models.IntegerField()),
                ('nombrePagesNB', models.IntegerField()),
                ('reliure', models.BooleanField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix \xe0 r\xe9gler')),
                ('estPaye', models.BooleanField()),
            ],
        ),
    ]
