# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
    ]
