# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
